name: Update PR branch version from base branch

inputs:
  version-guidance:
    description: The argument to supply to `poetry version`
    required: true
  github-token:
    description: >
      The github token you want to use, if not already set in your
      environment as GITHUB_TOKEN.
    required: false


outputs:
  new-version:
    description: The next semver version
    value: ${{ steps.update-version.outputs.new-version }}

runs:
  using: composite
  steps:
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0

    - uses: actions/checkout@v2
      with:
        # Checks out the branch that PR wants to merge into,
        # (i.e., the default branch).
        ref: ${{ github.event.pull_request.base.ref }}
        token: ${{ env.github_token }}
      env:
        github_token: ${{ inputs.github-token || env.GITHUB_TOKEN }}

    - run: echo ::set-output name=version::$(poetry version -s)
      id: get-version
      shell: bash

    - uses: actions/checkout@v2
      # Checks out the PR branch to update the version based
      # on the default branch version.
      with:
        token: ${{ env.github_token }}
      env:
        github_token: ${{ inputs.github-token || env.GITHUB_TOKEN }}

    - name: Update PR version to base_version+guidance
      env:
        BASE_VERSION: ${{ steps.get-version.outputs.version }}
      run: |
        set -x
        poetry version $BASE_VERSION
        if [[ "${{ inputs.version-guidance }}" != 'no-bump' ]]
        then
            poetry version ${{ inputs.version-guidance }}
        fi
        new_version=$(poetry version -s)
        echo ::set-output name=new-version::$new_version
      id: update-version
      shell: bash

    - run: >
        echo "::notice::Applied version ${base_version} (from branch '${base_branch}')
        and updated it to ${new_version} using ${guidance}-level guidance."
      env:
        base_version: ${{ steps.get-version.outputs.version }}
        new_version: ${{ steps.update-version.outputs.new-version }}
        base_branch: ${{ github.event.pull_request.base.ref }}
        guidance: ${{ inputs.version-guidance }}
      shell: bash


    - uses: EndBug/add-and-commit@v7
      env:
        version: ${{ steps.update-version.outputs.new-version }}
      with:
        add: pyproject.toml
        default_author: github_actions
        pull_strategy: NO-PULL
        push: ${{ steps.update-version.outputs.new-version &&  true || false }}
        message: "[Bot] Update version to ${{ env.version }}"
