name: Set up a Slack Notification Canvas
description: >
  Creates a notification canvas and sets the
  SLACK_CANVAS_ID environment variable. This
  action requires JSON input!

inputs:
  json:
    required: true
    description: >
      The JSON scaffolding for your canvas. See update-slack-workflow-canvas/README.md.
  gcloud-token:
    required: false

outputs:
  canvas-id:
    value: ${{ steps.create-canvas.outputs.canvas-id }}
runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcloud-token || env.GCLOUD_TOKEN }}"
    - uses: google-github-actions/setup-gcloud@v1.0.1
    - run: |
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://gcr.io
      shell: bash
    - uses: uwit-iam/actions/update-slack-workflow-canvas@0.1.4
      with:
        command: create-canvas
        json: "${{ inputs.json }}"
      id: create-canvas
    - run: echo "SLACK_CANVAS_ID=${{ steps.create-canvas.outputs.canvas-id }}" >> $GITHUB_ENV
      shell: bash
