name: "Update IAM Slack workflow canvas"

inputs:
  command:
    required: true
    description: |
      One of:
        - `create-canvas`
        - `create-step`
        - `update-workflow`
        - `add-artifact`
        - `finalize-workflow`
        - `get-canvas-json`
  canvas-id:
    required: true
    description: >
      Always required to be set. For convenience, you can set this in your
      workflow env as `SLACK_CANVAS_ID`. This identifies the canvas you
      are interacting with. This allows you interact with more than one canvas
      in a given workflow, if desired.
    default: ${{ env.SLACK_CANVAS_ID }}
  channel:
    required: false
    description: >
      Required when command is `create-canvas`; the channel to send messages to.
  description:
    required: false
    description: Required if command is `create-canvas`,
      `create-step`, or `add-artifact`.
  workflow-status:
    required: false
    description: |
      Always permitted. If set, will update the overall workflow status.
      Must be one of:
        - initializing
        - in progress
        - succeeded
        - failed

  step-status:
    required: false
    description: |
      Permitted if command is `create-step` or `update-workflow`,
      otherwise ignored.
      Must be one of:
        - not started
        - in progress
        - skipped
        - succeeded
        - failed
  step-id:
    required: false
    description: >
      Permitted with `create-step` and `update-workflow`; if provided, will allow you
      to update the step at a later time, even if it is not the current step. Otherwise,
      the step id will be autogenerated, and accessible from the output.

outputs:
  canvas-id:
    description: Output if command was `create-canvas`; the canvas id created.
  step-id:
    description: Output if command was `create-step`; the step id created.
  lock-id:
    description: >
      Output if command was one of `create-step`, `update-workflow`, or
      `add-artifact`; the lock id used during the transaction, in case debugging is
      needed.
  canvas-json:
    description: >
      Output from the command `get-canvas-json`; the, uh, canvas json.
  fingerprint:
    description: >
      Always output. The fingerprint of the action image, which may be useful
      for debugging or validation.

runs:
  using: docker
  image: gcr.io/uwit-mci-iam/update-slack-workflow-status-action:release
  env:
    ACTION_COMMAND: ${{ inputs.command }}
    ACTION_CHANNEL: ${{ inputs.channel }}
    ACTION_DESCRIPTION: ${{ inputs.description }}
    ACTION_WF_STATUS: ${{ inputs.workflow-status }}
    ACTION_STEP_STATUS: ${{ inputs.step-status }}
    ACTION_STEP_ID: ${{ inputs.step-id }}
    ACTION_CANVAS: ${{ inputs.canvas-id }}
