name: Configure gcloud and docker

inputs:
  gcloud-token:
    description: The Base-64 encoded service account token
    required: true
  gcloud-version:
    required: true
    default: 297.0.1
    description: >
      The version of gcloud CLI you want to set up. 297.0.1 is
      the recommended default due to issues with docker-compose
      in later versions. Only override this if you do not
      need to use docker-compose in your workflow.


runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcr-token }}
    - uses: google-github-actions/setup-gcloud@v0
      with:
        # This version has to stay pinned in order
        # to work with docker-compose; there is a bug
        # either in Docker's or Google's software.
        # Ref: https://stackoverflow.com/questions/65295958/docker-compose-not-working-with-gcloud-cannot-find-openssl
        version: 297.0.1
    - run: |
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://gcr.io
      shell: bash
